version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql-africacrypto
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: africacrypto_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  africacrypto-backend:
    build: .
    container_name: africacrypto-backend
    ports:
      - "8080:8080"
    environment:
      JWT_SECRET: ${JWT_SECRET}
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/africacrypto_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - mysql

volumes:
  mysql_data:
